# Generated by Django 5.1.6 on 2025-06-29 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twccapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('youtube_url', models.URLField()),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='video_thumbnails/')),
            ],
        ),
    ]
