# Generated by Django 5.2.3 on 2025-07-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twccapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliderimage',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
