# Generated by Django 5.2.3 on 2025-07-01 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twccapp', '0002_contactmessage'),
        ('twccapp', '0002_video'),
    ]

    operations = [
    ]
