# Generated by Django 5.2.3 on 2025-07-11 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twccapp', '0003_advertisement'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Upload PDF document (optional)', null=True, upload_to='advertisements/pdfs/'),
        ),
    ]
