# Generated by Django 5.2.3 on 2025-07-11 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twccapp', '0004_advertisement_pdf_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='pdf_file',
        ),
    ]
