# Generated by Django 5.2.3 on 2025-07-15 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twccapp', '0005_remove_advertisement_pdf_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leadership',
            options={'ordering': ['category', 'order'], 'verbose_name_plural': 'Leadership Team'},
        ),
        migrations.AddField(
            model_name='leadership',
            name='category',
            field=models.CharField(choices=[('board', 'Board of Directors'), ('leadership', 'Leadership Team'), ('staff', 'Staff Members')], default='staff', max_length=20),
        ),
    ]
