# Generated by Django 5.2.3 on 2025-07-15 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twccapp', '0006_alter_leadership_options_leadership_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='image',
        ),
        migrations.AddField(
            model_name='services',
            name='icon',
            field=models.CharField(choices=[('fa-money-bill-wave', 'Financial (money bill)'), ('fa-handshake', 'Networking (handshake)'), ('fa-chart-line', 'Capacity (growth chart)'), ('fa-bullhorn', 'Advocacy (megaphone)'), ('fa-users', 'Team (users)'), ('fa-globe', 'Global (globe)')], default='fa-handshake', max_length=50),
        ),
    ]
