# Generated by Django 5.2.3 on 2025-07-15 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twccapp', '0009_rename_description_galleryimage_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='summary',
            field=models.TextField(),
        ),
    ]
