# Generated by Django 5.2.3 on 2025-07-15 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twccapp', '0010_alter_galleryimage_content_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GalleryImage',
        ),
    ]
