# Generated by Django 5.2.3 on 2025-07-16 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twccapp', '0012_galleryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('pdf_file', models.FileField(upload_to='newsletters/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
