# Generated by Django 5.2.3 on 2025-07-16 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twccapp', '0013_newsletterpdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
