# Generated by Django 5.2.3 on 2025-07-17 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twccapp', '0014_galleryimage_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='description',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='created_at',
            new_name='date_posted',
        ),
        migrations.RemoveField(
            model_name='project',
            name='is_active',
        ),
        migrations.AddField(
            model_name='project',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='summary',
            field=models.TextField(default='Default summary text'),
        ),
    ]
