# Generated by Django 5.2.3 on 2025-07-17 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twccapp', '0015_rename_description_project_content_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'ordering': ['order', '-uploaded_at']},
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='content',
            field=models.TextField(default='Default content'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='summary',
            field=models.TextField(default='Default summary'),
        ),
    ]
