# Generated by Django 5.2.3 on 2025-08-05 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twccapp', '0018_upcomingevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('constitution', 'Constitution'), ('strategic_plan', 'Strategic Plan'), ('code_of_conduct', 'Code of Conduct')], help_text='Type of document', max_length=20, unique=True)),
                ('pdf_file', models.FileField(help_text='Upload PDF file', upload_to='documents/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
            },
        ),
    ]
