# Generated by Django 5.2.3 on 2025-08-11 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twccapp', '0019_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='ad_type',
            field=models.CharField(choices=[('upcoming', 'Upcoming Event'), ('recent', 'Recent Update')], default='upcoming', max_length=10),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='advertisements/pdfs/'),
        ),
    ]
