# Generated by Django 5.2.3 on 2025-08-11 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twccapp', '0020_advertisement_ad_type_advertisement_pdf_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='ad_type',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='pdf_file',
        ),
    ]
