# Generated by Django 5.2.3 on 2025-08-13 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twccapp', '0022_recentadvert'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('annual_report', 'Annual Report'), ('research_paper', 'Research Paper & Study'), ('strategic_plan', 'Strategic Plan'), ('newsletter', 'Newsletter'), ('press_release', 'Press Release')], max_length=20)),
                ('title', models.CharField(help_text="Report title (e.g., '2023 Annual Report')", max_length=200)),
                ('pdf_file', models.FileField(upload_to='report/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
