# Generated by Django 5.2.3 on 2025-08-14 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twccapp', '0024_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload a profile photo of the person giving the testimonial', null=True, upload_to='testimonials/'),
        ),
    ]
