# Generated by Django 5.2.3 on 2025-08-18 08:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twccapp', '0025_testimonial_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpactStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('content', models.TextField()),
                ('summary', models.TextField()),
                ('image', models.ImageField(upload_to='impact_stories/')),
                ('category', models.CharField(choices=[('fashion', 'Women in Sustainable Fashion'), ('markets', 'Women in Regional Markets'), ('youth', 'Youth-Led Innovations'), ('agriculture', 'Women in Agriculture'), ('other', 'Other Sectors')], max_length=50)),
                ('featured', models.BooleanField(default=False)),
                ('date_published', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Impact Stories',
                'ordering': ['-date_published'],
            },
        ),
    ]
