# Generated by Django 5.2.3 on 2025-08-18 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twccapp', '0026_impactstory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impactstory',
            name='category',
            field=models.CharField(choices=[('all', 'All Stories'), ('fashion', 'Women in Sustainable Fashion'), ('markets', 'Women in Regional Markets'), ('youth', 'Youth-Led Innovations'), ('agriculture', 'Women in Agriculture'), ('other', 'Other Sectors')], max_length=50),
        ),
    ]
