# Generated by Django 5.2.3 on 2025-08-19 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twccapp', '0027_alter_impactstory_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impactstory',
            name='slug',
        ),
    ]
