# Generated by Django 5.2.3 on 2025-08-20 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twccapp', '0028_remove_impactstory_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='icon',
        ),
        migrations.AddField(
            model_name='services',
            name='category',
            field=models.CharField(choices=[('financial_linkage', 'Financial Linkage'), ('networking_marketing', 'Networking and Marketing'), ('capacity_building', 'Capacity Building'), ('advocacy', 'Advocacy'), ('market_access', 'Market Access and Digitalization')], default=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='services',
            name='summary',
            field=models.TextField(default='Service summary'),
        ),
    ]
