# Generated by Django 5.2.3 on 2025-08-20 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twccapp', '0029_remove_services_icon_services_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliderimage',
            name='redirect_url',
            field=models.URLField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
