# Generated by Django 5.2.3 on 2025-08-21 10:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twccapp', '0030_sliderimage_redirect_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='YouthStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('summary', models.TextField()),
                ('image', models.ImageField(upload_to='youth_stories/')),
                ('category', models.CharField(choices=[('success', 'Youth Success Stories'), ('involved', 'Get Involved'), ('events', 'Events & Activities'), ('resources', 'Resources for Youth'), ('leadership', 'Leadership Training'), ('entrepreneurship', 'Entrepreneurship Bootcamp'), ('digital', 'Digital Skills Workshops'), ('trade', 'Youth Trade Missions')], max_length=50)),
                ('featured', models.BooleanField(default=False)),
                ('date_published', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Youth Stories',
                'ordering': ['-date_published'],
            },
        ),
    ]
