# Generated by Django 5.2.3 on 2025-09-15 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twccapp', '0032_donation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('annual_report', 'Annual Report'), ('research_paper', 'Research Paper & Study'), ('strategic_plan', 'Strategic Plan'), ('newsletter', 'Newsletter'), ('press_release', 'Press Release'), ('company_profile', 'Company Profile')], max_length=20),
        ),
    ]
